namespace DeepCore.Client.Misc
{
    internal enum EventCodes : byte
    {
        VoiceData = 1,
        ServerMessage = 2,
        MasterClientSync = 4,
        CachedEvent,
        MasterClientSyncFinished,
        VRChatRPC,
        SerializedData,
        InterestManagement,
        SerializedDataReliable,
        Unknown10,
        Unknown11,
        SerializedDataUnreliable,
        ReliableFlatbuffer,
        ObjectSync = 16,
        Unknown17,
        JoinWorld = 20,
        ObjectOwnership = 22,
        Moderations = 33,
        PhotonEventLimits,
        PhotonHeartbeat,
        AvatarRefresh = 40,
        SetPlayerData = 42,
        Unknown43,
        OwnChatbox,
        OnLoaded = 51,
        PlayerReady = 53,
        PhysBonesPermissions = 60,
        EACHeartBeat = 66,
        Portal = 70,
        EmojiSend = 73,
        PhotonRPC = 200,
        SendSerialize,
        Instantiate = 202,
        CloseConnection,
        Destroy,
        RemoveCachedRPCs,
        SendSerializeReliable,
        DestroyPlayer,
        AssignMasterClient,
        OwnershipRequest,
        OwnershipTransfer,
        VacantViewIds,
        LevelReload,
        PhotonAppId = 220,
        AuthEvent = 223,
        LobbyStats,
        AppStats = 226,
        Match,
        QueueState,
        GameListUpdate,
        GameList,
        CacheSliceChanged = 250,
        ErrorInfo,
        SetProperties = 253,
        LeavePhoton = 254,
        JoinPhoton = 255,
    }
}
